export const mockPosts = [
  {
    id: 1,
    username: "Bloom Threads",
    vendorNumber: "+2348012345678",
    vendorDetail:
      "Bloom Threads offers expertly crafted clothing for every occasion. We focus on quality and unique designs that allow your personal style to bloom.",
    caption:
      "Your wardrobe called… it wants an upgrade 👗💖 Shop the new drop now! This flowery patterned sundress is perfect for a summer day. The light, airy fabric will keep you cool and comfortable, while the vibrant floral",
    likes: 120,
    userpic: "/new-profile-image.png",
    comments: 34,
    shares: 10,
    views: 100,
    productName: "Flowery Patterned Sundress",
    rating: 4.8,
    reviews: 24,
    price: 12500,
    postTime: "1hr",
    description:
      "This flowery patterned sundress is perfect for a summer day. The light, airy fabric will keep you cool and comfortable, while the vibrant floral pressings, prestigeous.",
    colors: ["white", "pink", "black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    media: [
      { type: "video", src: "/video.mp4" },
      { type: "image", src: "/feed-image2.png" },
      { type: "image", src: "/feed-image.png" },
    ],
    musicTrack: "Summer Renaissance - Beyoncé",
    estDelivery: "2-7 days",
    deliveryLocation: "Lagos, Ilorin, Abuja",
    reviewsData: [
      {
        id: 101,
        user: "Adetayo Gbemisola",
        rating: 5,
        date: "19/09/25",
        text: "The design is both stylish and comfortable, making it easy to dress up or down. I love the vibrant colors and the flattering fit that accentuates my figure. Overall, this sundress is a fantastic addition to my wardrobe, and I highly recommend it to anyone looking for a chic and versatile piece!",
      },
      {
        id: 102,
        user: "Anu Folarin",
        rating: 1,
        date: "19/09/25",
        text: "The dress is very nice. I love it so much. 😍",
      },
      {
        id: 103,
        user: "Jago Chiamaka",
        rating: 5,
        date: "19/09/25",
        text: "The fabric is soft and breathable, perfect for warm days. I love how it flows and the unique pattern really stands out; it’s versatile enough for both casual outings and special occasions. I can’t recommend it enough for anyone wanting to elevate their summer style!",
      },
      {
        id: 104,
        user: "Bimbo Adekunle",
        rating: 4,
        date: "19/09/25",
        text: "Good quality for the price, fits well. Fast shipping. A must-buy!",
      },
      {
        id: 105,
        user: "Tunde Olayinka",
        rating: 5,
        date: "19/09/25",
        text: "Absolutely stunning! Looks exactly like the picture. Five stars!",
      },
    ],
    commentsData: [
      {
        id: 1,
        user: "Temiloluwa Gbolahan",
        userpic: "/new-profile-image.png",
        text: "I got something like this for my girl, and it's super pretty!",
        timeAgo: "19/09/25",
        likes: 13,
        replies: [
          {
            id: 11,
            user: "Julia Adeniyi",
            userpic: "/new-profile-image.png",
            text: "Did you get it from this vendor?",
            timeAgo: "19/09/25",
            likes: 13,
            replyingTo: "Adetayo Gbemisola",
          },
        ],
      },
      {
        id: 2,
        user: "Adetayo Gbemisola",
        text: "I bought one for my friend, and she adores it! It's held up really well.",
        timeAgo: "5d",
        likes: 13,
        replies: [],
      },
    ],
  },

  {
    id: 2,
    username: "Sarah",
    vendorNumber: "+2348011236578",
    vendorDetail: "",
    caption: "Chilling on a Sunday 🌴",
    likes: 200,
    userpic: "/feed-image.png",
    comments: 15,
    shares: 8,
    views: 10,
    productName: "yellow Sundress",
    rating: 3.8,
    reviews: 56,
    price: 9000,
    postTime: "3 days",
    description:
      "This Yellow sundress is perfect for a summer day. The light, airy fabric will keep you cool and comfortable, while the vibrant floral pressings, prestigeous.",
    colors: ["white", "pink", "black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    media: [
      { type: "image", src: "/feed-image2.png" },
      { type: "image", src: "/feed-image.png" },
      { type: "video", src: "/video.mp4" },
    ],
    musicTrack: "Good days - SZA",
    estDelivery: "15-20 days",
    deliveryLocation: "Lagos, Ogun, Oyo",
    reviewsData: [
      {
        id: 101,
        user: "Adetayo Gbemisola",
        rating: 5,
        date: "19/09/25",
        text: "The design is both stylish and comfortable, making it easy to dress up or down. I love the vibrant colors and the flattering fit that accentuates my figure. Overall, this sundress is a fantastic addition to my wardrobe, and I highly recommend it to anyone looking for a chic and versatile piece!",
      },
      {
        id: 102,
        user: "Anu Folarin",
        rating: 4,
        date: "19/09/25",
        text: "The dress is very nice. I love it so much. 😍",
      },
      {
        id: 103,
        user: "Ugo Chiamaka",
        rating: 5,
        date: "19/09/25",
        text: "The fabric is soft and breathable, perfect for warm days. I love how it flows and the unique pattern really stands out; it’s versatile enough for both casual outings and special occasions. I can’t recommend it enough for anyone wanting to elevate their summer style!",
      },
      {
        id: 104,
        user: "Bimbo Adekunle",
        rating: 4,
        date: "19/09/25",
        text: "Good quality for the price, fits well. Fast shipping. A must-buy!",
      },
      {
        id: 105,
        user: "Tunde Olayinka",
        rating: 5,
        date: "19/09/25",
        text: "Absolutely stunning! Looks exactly like the picture. Five stars!",
      },
    ],
    commentsData: [], // Empty comments for post ID 2
  },

  {
    id: 3,
    username: "La vida",
    vendorNumber: "+2349022347645",
    vendorDetail: "OOMOOO THIS THING EHHN!!!",
    caption: "Building a website on a meet",
    likes: 200,
    userpic: "/feed-image2.png",
    comments: 15,
    shares: 8,
    views: 167,
    productName: "Anker Speaker",
    rating: 4.8,
    reviews: 14,
    price: 122500,
    postTime: "1 week",
    description:
      "This speaker has an ultra bass that gives you that pure music vibe",
    colors: ["white", "pink", "black"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    media: [
      { type: "image", src: "/feed-image2.png" },
      { type: "video", src: "/video.mp4" },
      { type: "image", src: "/feed-image.png" },
    ],
    musicTrack: "FE!N -  Travis Scott",
    estDelivery: "7-15 days",
    deliveryLocation: "World wide",
    reviewsData: [
      {
        id: 101,
        user: "Adetayo Gbemisola",
        rating: 5,
        date: "19/09/25",
        text: "The design is both stylish and comfortable, making it easy to dress up or down. I love the vibrant colors and the flattering fit that accentuates my figure. Overall, this sundress is a fantastic addition to my wardrobe, and I highly recommend it to anyone looking for a chic and versatile piece!",
      },
      {
        id: 102,
        user: "Anu Folarin",
        rating: 2,
        date: "19/09/25",
        text: "The dress is very nice. I love it so much. 😍",
      },
      {
        id: 103,
        user: "Ugo Chiamaka",
        rating: 5,
        date: "19/09/25",
        text: "The fabric is soft and breathable, perfect for warm days. I love how it flows and the unique pattern really stands out; it’s versatile enough for both casual outings and special occasions. I can’t recommend it enough for anyone wanting to elevate their summer style!",
      },
      {
        id: 104,
        user: "Bimbo Adekunle",
        rating: 4,
        date: "19/09/25",
        text: "Good quality for the price, fits well. Fast shipping. A must-buy!",
      },
      {
        id: 105,
        user: "Tunde Olayinka",
        rating: 5,
        date: "19/09/25",
        text: "Absolutely stunning! Looks exactly like the picture. Five stars!",
      },
    ],
    commentsData: [], // Empty comments for post ID 3
  },
];
