const products = [
  {
    id: 1,
    name: "Jacob's Frosty",
    category: "Ice Cream",
    image: "/jacob.jpeg",
    contact: "08012345678",
    shortDescription:
      "Serving up creamy, handcrafted ice cream in a variety of delicious flavors",
    address: "23 Marina Street, Calabar, Cross River State, Nigeria",
    productItems: [
      {
        id: 101,
        name: "Vanilla Swirl",
        price: "1,500",
        image: "/vanilla.jpg",
        description:
          "Classic creamy vanilla ice cream made with real vanilla beans",
      },
      {
        id: 102,
        name: "Chocolate Delight",
        price: "1,800",
        image: "/chocolate.jpg",
        description: "Rich and creamy chocolate ice cream for chocolate lovers",
      },
    ],
  },
  {
    id: 2,
    name: "Aubergint",
    category: "Fresh Food",
    image: "/auber.jpeg",
    contact: "08012345678",
    shortDescription: "Fresh, affordable, and always stocked",
    address: "15 Oladipo Avenue, Ikeja, Lagos State, Nigeria",
    productItems: [
      {
        id: 201,
        name: "Organic Tomatoes",
        price: "500/kg",
        image: "/tomatoes.jpeg",
        description: "Fresh organic tomatoes directly from the farm",
      },
      {
        id: 202,
        name: "Green Peppers",
        price: "800/kg",
        image: "/peppers.jpeg",
        description: "Crisp and fresh green peppers for your cooking needs",
      },
    ],
  },
  {
    id: 3,
    name: "Elite Clippers",
    category: "Barbershop",
    image: "/elite.jpeg",
    contact: "08012345678",
    shortDescription:
      "Step into Elite Clippers for the freshest fades and sharpest trims",
    address: "28 Adebola Street, Surulere, Lagos State, Nigeria",
    productItems: [
      {
        id: 301,
        name: "Regular Haircut",
        price: "2,000",
        image: "/haircut.jpeg",
        description: "Standard men’s haircut with a professional touch",
      },
      {
        id: 302,
        name: "Beard Trim",
        price: "1,500",
        image: "/beard.jpeg",
        description: "Sharp and clean beard trim to keep you looking fresh",
      },
    ],
  },
  {
    id: 4,
    name: "Mkzay's Consortium",
    category: "Antiques",
    image: "/jacob.jpeg",
    contact: "08012345678",
    shortDescription:
      "Explore our collection of rare and classic antiques from different eras",
    address: "23 Marina Street, Calabar, Cross River State, Nigeria",
    productItems: [
      {
        id: 401,
        name: "Victorian Vase",
        price: "50,000",
        image: "/vase.jpeg",
        description: "Elegant handcrafted Victorian-era porcelain vase",
      },
      {
        id: 402,
        name: "Antique Clock",
        price: "80,000",
        image: "/clock.jpeg",
        description: "Classic wooden antique clock from the 19th century",
      },
    ],
  },
  {
    id: 5,
    name: "Sunset Café",
    category: "Café",
    image: "/elite.jpeg",
    contact: "08012345678",
    shortDescription: "Brewed to perfection, served with love",
    address: "45 Admiralty Way, Lekki, Lagos, Nigeria",
    productItems: [
      {
        id: 501,
        name: "Espresso Shot",
        price: "700",
        image: "/vanilla.jpg",
        description: "Strong and aromatic espresso to kickstart your day",
      },
      {
        id: 502,
        name: "Cappuccino",
        price: "1,200",
        image: "/chocolate.jpg",
        description: "Smooth cappuccino with a creamy frothy top",
      },
    ],
  },
  {
    id: 6,
    name: "Urban Kicks",
    category: "Footwear",
    image: "/auber.jpeg",
    contact: "08012345678",
    shortDescription: "Step out in style with the latest sneaker trends",
    address: "10 Campbell Street, Victoria Island, Lagos, Nigeria",
    productItems: [
      {
        id: 601,
        name: "Retro Sneakers",
        price: "15,000",
        image: "/tomatoes.jpeg",
        description: "Classic retro sneakers with a modern touch",
      },
      {
        id: 602,
        name: "Leather Boots",
        price: "25,000",
        image: "/peppers.jpeg",
        description: "Premium leather boots for casual and formal outings",
      },
    ],
  },
  {
    id: 7,
    name: "Tech Haven",
    category: "Electronics",
    image: "/jacob.jpeg",
    contact: "08012345678",
    shortDescription: "Your one-stop shop for the latest gadgets",
    address: "99 Ikorodu Road, Lagos, Nigeria",
    productItems: [
      {
        id: 701,
        name: "Wireless Headphones",
        price: "10,000",
        image: "/vase.jpeg",
        description: "Noise-canceling headphones with superior sound quality",
      },
      {
        id: 702,
        name: "Smart Watch",
        price: "20,000",
        image: "/clock.jpeg",
        description:
          "Stay connected with this stylish and functional smartwatch",
      },
    ],
  },
  {
    id: 8,
    name: "Healthy Bites",
    category: "Food",
    image: "/elite.jpeg",
    contact: "08012345678",
    shortDescription:
      "Nutritious and delicious meals for a healthier lifestyle",
    address: "33 Herbert Macaulay Way, Yaba, Lagos, Nigeria",
    productItems: [
      {
        id: 801,
        name: "Grilled Chicken Salad",
        price: "3,500",
        image: "/vanilla.jpg",
        description: "Fresh greens with tender grilled chicken",
      },
      {
        id: 802,
        name: "Avocado Toast",
        price: "2,000",
        image: "/chocolate.jpg",
        description: "Smashed avocado on crunchy whole-grain bread",
      },
    ],
  },
  {
    id: 9,
    name: "Royal Jewelry",
    category: "Luxury",
    image: "/auber.jpeg",
    contact: "08012345678",
    shortDescription: "Timeless pieces for every occasion",
    address: "14 Banuso Street, Ikoyi, Lagos, Nigeria",
    productItems: [
      {
        id: 901,
        name: "Gold Necklace",
        price: "100,000",
        image: "/tomatoes.jpeg",
        description: "Elegant gold necklace with a stunning pendant",
      },
      {
        id: 902,
        name: "Diamond Ring",
        price: "200,000",
        image: "/peppers.jpeg",
        description: "A beautiful diamond ring for special moments",
      },
    ],
  },
  {
    id: 10,
    name: "Bespoke Tailors",
    category: "Fashion",
    image: "/jacob.jpeg",
    contact: "08012345678",
    shortDescription: "Custom-made outfits designed just for you",
    address: "22 Allen Avenue, Ikeja, Lagos, Nigeria",
    productItems: [
      {
        id: 1001,
        name: "Men’s Suit",
        price: "50,000",
        image: "/vase.jpeg",
        description: "Tailored suit for formal occasions",
      },
      {
        id: 1002,
        name: "Ladies Gown",
        price: "30,000",
        image: "/clock.jpeg",
        description: "Elegant evening gown for special events",
      },
    ],
  },
  {
    id: 11,
    name: "Swift Couriers",
    category: "Logistics",
    image: "/elite.jpeg",
    contact: "08012345678",
    shortDescription: "Fast and reliable delivery services",
    address: "5 Ojuelegba Road, Surulere, Lagos, Nigeria",
    productItems: [
      {
        id: 1101,
        name: "Express Delivery",
        price: "5,000",
        image: "/vanilla.jpg",
        description: "Same-day delivery within Lagos",
      },
      {
        id: 1102,
        name: "Nationwide Shipping",
        price: "10,000",
        image: "/chocolate.jpg",
        description: "Reliable shipping to any state in Nigeria",
      },
    ],
  },
  {
    id: 12,
    name: "Glow Skincare",
    category: "Beauty",
    image: "/auber.jpeg",
    contact: "08012345678",
    shortDescription: "Glow naturally with our organic skincare products",
    address: "17 Toyin Street, Ikeja, Lagos, Nigeria",
    productItems: [
      {
        id: 1201,
        name: "Hydrating Face Mask",
        price: "5,000",
        image: "/tomatoes.jpeg",
        description: "A refreshing mask for smooth, glowing skin",
      },
      {
        id: 1202,
        name: "Body Scrub",
        price: "7,000",
        image: "/peppers.jpeg",
        description: "Exfoliating scrub for silky soft skin",
      },
    ],
  },
];

export default products;
