import {
  Home,
  User,
  ShoppingCart,
  Search,
  MessageSquare,
  PlusCircle,
  Heart,
  Share2,
  MoreVertical,
  Bell,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  X,
  Check,
  Trash2,
  Edit3,
  Camera,
  UtensilsCrossed,
  Wallet,
  CreditCard,
  Banknote,
  ArrowLeft,
  ArrowRight,
  Loader2,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Menu,
  MapPin,
  Phone,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Sun,
  Moon,
  Filter,
  SortAsc,
  Download,
  Upload,
  RefreshCw,
  Play,
  Pause,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Send,
  Paperclip,
  Image as ImageIcon,
  Video,
  Smile,
  Hash,
  AtSign,
  Globe,
  Clock,
  Calendar,
  Star,
  Flag,
  Bookmark,
  MoreHorizontal,
  Copy,
  ExternalLink,
  Link as LinkIcon,
  QrCode,
  ScanLine,
  UserPlus,
  Users,
  Store,
  Package,
  Truck,
  Receipt,
  FileText,
  HelpCircle,
  Shield,
  ShieldCheck,
  Award,
  BadgeCheck,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Flame,
  Sparkles,
  Gift,
  Ticket,
  Tag,
  Percent,
  DollarSign,
  Coins,
  Wallet as WalletIcon,
  Landmark,
  Building2,
  Building,
  Home as HomeBuilding,
  MapPinned,
  Navigation,
  LocateFixed,
  Locate,
  Compass,
  Search as SearchIcon,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  Scissors,
  Wand2,
  Magic,
  Wand,
  Sparkle,
  Lightbulb,
  Lamp,
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  Snowflake,
  Flame as FlameIcon,
  FireExtinguisher,
  AlertTriangle,
  AlertOctagon,
  Skull,
  Ghost,
  Heart as HeartIcon,
  HeartCrack,
  HeartHandshake,
  ThumbsUp,
  ThumbsDown,
  Hand,
  HandMetal,
  Fist,
  Peace,
  Victory,
  Rock,
  ScissorsHand,
  Paper,
  Plus,
  Minus,
  Divide,
  Multiply,
  Equal,
  NotEqual,
  GreaterThan,
  LessThan,
  Infinity,
  Pi,
  Sigma,
  FunctionSquare,
  Calculator,
  Binary,
  Code,
  Code2,
  Terminal,
  Command,
  Keyboard,
  Mouse,
  MousePointer2,
  MousePointerClick,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveHorizontal,
  MoveVertical,
  GripVertical,
  GripHorizontal,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  AlignStartVertical,
  AlignCenterVertical,
  AlignEndVertical,
  Space,
  Baseline,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Highlighter,
  Palette,
  Paintbrush,
  PaintBucket,
  SprayCan,
  Eraser,
  PenTool,
  Pencil,
  Edit,
  FileEdit,
  FilePlus,
  FileMinus,
  FileX,
  File,
  FileText as FileTextIcon,
  FileCode,
  FileJson,
  FileSpreadsheet,
  FilePieChart,
  FileBarChart,
  FileAudio,
  FileVideo,
  FileImage,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderTree,
  Folders,
  Archive,
  ArchiveRestore,
  ArchiveX,
  Inbox,
  Mail as MailIcon,
  MailOpen,
  MailPlus,
  MailMinus,
  MailX,
  MailCheck,
  MailQuestion,
  MailWarning,
  MessageCircle,
  MessageSquare as MessageSquareIcon,
  MessageSquarePlus,
  MessageSquareMinus,
  MessageSquareX,
  MessageSquareCheck,
  MessagesSquare,
  MessagesCircle,
  Sticker,
  Laugh,
  Meh,
  Annoyed,
  Frown,
  Angry,
  Smile as SmileIcon,
  SmilePlus,
  SmileMinus,
  Ghost as GhostIcon,
  Cat,
  Dog,
  Bird,
  Fish,
  Rabbit,
  Turtle,
  Bug,
  Beetle,
  Ant,
  Spider,
  Rat,
  Squirrel,
  PawPrint,
  Footprints,
  Clover,
  Flower,
  Flower2,
  Trees,
  TreeDeciduous,
  TreePine,
  Leaf,
  Mountain,
  MountainSnow,
  Volcano,
  Waves,
  Tent,
  Camping,
  Car,
  CarFront,
  Bus,
  BusFront,
  Train,
  TrainFront,
  Plane,
  PlaneTakeoff,
  PlaneLanding,
  Rocket,
  Satellite,
  Ship,
  Sailboat,
  Anchor,
  Navigation2,
  Compass as CompassIcon,
  Map,
  Map as MapIcon,
  Pizza,
  Hamburger,
  Soup,
  ChefHat,
  Utensils,
  ForkKnife,
  CupSoda,
  Coffee,
  Beer,
  Wine,
  GlassWater,
  IceCream,
  Cake,
  Cookie,
  Candy,
  Cherry,
  Apple,
  Banana,
  Carrot,
  Beef,
  FishSymbol,
  Egg,
  EggFried,
  Milk,
  Wheat,
  Croissant,
  Sandwich,
  Salad,
  Popcorn,
  Donut,
  Cupcake,
  Lollipop,
  Beef as Meat,
  Drumstick,
  Bone,
  Axe,
  Sword,
  Shield as ShieldIcon,
  Target,
  Crosshair,
  Focus,
  Scan,
  ScanFace,
  ScanLine as ScanLineIcon,
  ScanSearch,
  Fingerprint,
  FaceId,
  Contact,
  Contact2,
  UserCircle,
  UserCog,
  UserCheck,
  UserX,
  UserMinus,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
  Users2,
  UsersRound,
  Group,
  Baby,
  PersonStanding,
  Accessibility,
  Armchair,
  Bath,
  Bed,
  BedDouble,
  BedSingle,
  Blinds,
  Chair,
  DoorClosed,
  DoorOpen,
  Fan,
  Lamp as LampIcon,
  Lightbulb as LightbulbIcon,
  Tv,
  Monitor,
  MonitorSmartphone,
  Laptop,
  Tablet,
  Smartphone,
  Watch,
  Clock as ClockIcon,
  Timer,
  Stopwatch,
  Hourglass,
  History,
  Rotate3d,
  Repeat,
  Repeat1,
  Shuffle,
  List,
  ListFilter,
  ListOrdered,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Table,
  Grid3x3,
  Grid2x2,
  Grid,
  Rows2,
  Columns2,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  PanelLeftClose,
  PanelRightClose,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  Navigation as NavigationIcon,
  MoreVertical as MoreVerticalIcon,
  MoreHorizontal as MoreHorizontalIcon,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  ChevronUp,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ArrowUp,
  ArrowDown,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowBigDown,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftUp,
  CornerLeftDown,
  CornerRightUp,
  CornerRightDown,
  Trash,
  Trash2 as Trash2Icon,
  Delete,
  Edit2,
  Edit3 as Edit3Icon,
  PenSquare,
  FileSignature,
  Clipboard,
  ClipboardCopy,
  ClipboardList,
  ClipboardCheck,
  ClipboardX,
  ClipboardPaste,
  ClipboardType,
  Copy as CopyIcon,
  Cut,
  Layers,
  Layers2,
  Stack,
  BringToFront,
  SendToBack,
  AlignCenterHorizontal,
  AlignCenterVertical as AlignCenterVerticalIcon,
  Radius,
  Diameter,
  Square,
  Circle,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Diamond,
  Trapezoid,
  Parallelogram,
  Cylinder,
  Cone,
  Cube,
  Box,
  Package as PackageIcon,
  Package2,
  PackageOpen,
  PackageX,
  PackageCheck,
  PackageSearch,
  Container,
  Truck as TruckIcon,
  TruckDelivery,
  Luggage,
  Briefcase,
  Suitcase,
  Backpack,
  ShoppingBag,
  ShoppingBasket,
  Store as StoreIcon,
  Warehouse,
  Factory,
  Hotel,
  School,
  Building as BuildingIcon,
  Building2 as Building2Icon,
  Hospital,
  Church,
  Castle,
  Landmark as LandmarkIcon,
  Banknote as BanknoteIcon,
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon2,
  PiggyBank,
  Receipt as ReceiptIcon,
  ReceiptCent,
  ReceiptEuro,
  ReceiptPound,
  ReceiptRupee,
  ReceiptYen,
  ReceiptYuan,
  ReceiptIndianRupee,
  ReceiptRussianRuble,
  ReceiptText,
  Ticket as TicketIcon,
  TicketCheck,
  TicketX,
  TicketMinus,
  TicketPlus,
  TicketPercent,
  Tags,
  Tag as TagIcon,
  ShoppingCart as ShoppingCartIcon,
  ShoppingBag as ShoppingBagIcon,
  Gift as GiftIcon,
  Award as AwardIcon,
  Medal,
  Trophy,
  Crown,
  Gem,
  Diamond as DiamondIcon,
  Ruby,
  Star as StarIcon,
  Sparkles as SparklesIcon,
  Zap as ZapIcon,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryMedium,
  BatteryLow,
  BatteryWarning,
  Power,
  Plug,
  PlugZap,
  Cable,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothConnected,
  BluetoothSearching,
  BluetoothOff,
  Cast,
  Airplay,
  MonitorPlay,
  MonitorPause,
  MonitorStop,
  MonitorX,
  SmartphoneCharging,
  SmartphoneNfc,
  TabletSmartphone,
  Headphones,
  Speaker,
  Volume,
  Volume1,
  Music,
  Music2,
  Music3,
  Music4,
  Play as PlayIcon,
  PlayCircle,
  Pause as PauseIcon,
  PauseCircle,
  StopCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat as RepeatIcon,
  Shuffle as ShuffleIcon,
  Mic,
  Mic2,
  MicOff,
  Webcam,
  Video as VideoIcon,
  VideoOff,
  Film,
  Clapperboard,
  Tv as TvIcon,
  Radio,
  RadioReceiver,
  Podcast,
  Rss,
  Wifi as WifiIcon,
  Signal,
  SignalHigh,
  SignalMedium,
  SignalLow,
  SignalZero,
  QrCode as QrCodeIcon,
  Barcode,
  Hash as HashIcon,
  AtSign as AtSignIcon,
  Globe as GlobeIcon,
  Globe2,
  Languages,
  Book,
  BookOpen,
  BookX,
  BookCheck,
  Bookmark as BookmarkIcon,
  BookmarkX,
  BookmarkMinus,
  BookmarkPlus,
  Library,
  GraduationCap,
  School as SchoolIcon,
  Calculator as CalculatorIcon,
  Ruler,
  Triangle as TriangleIcon,
  RulerDimensionLine,
  DraftingCompass,
  PenTool as PenToolIcon,
  Pencil as PencilIcon,
  PencilRuler,
  Paintbrush as PaintbrushIcon,
  PaintBucket as PaintBucketIcon,
  Palette as PaletteIcon,
  SwatchBook,
  Blend,
  Layers as LayersIcon,
  Layout as LayoutIcon,
  LayoutGrid as LayoutGridIcon,
  LayoutList as LayoutListIcon,
  LayoutTemplate as LayoutTemplateIcon,
  LayoutDashboard,
  Table2,
  Columns3,
  Grid3X3,
  FlipHorizontal as FlipHorizontalIcon,
  FlipVertical as FlipVerticalIcon,
  ScreenShare,
  ScreenShareOff,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Watch as WatchIcon,
  Glasses,
  Sunglasses,
  Shirt,
  Footprints as FootprintsIcon,
} from "lucide-react";

// Icon mapping for dynamic icon rendering
const iconMap = {
  home: Home,
  user: User,
  cart: ShoppingCart,
  search: Search,
  message: MessageSquare,
  create: PlusCircle,
  heart: Heart,
  share: Share2,
  more: MoreVertical,
  bell: Bell,
  settings: Settings,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  x: X,
  check: Check,
  trash: Trash2,
  edit: Edit3,
  camera: Camera,
  utensils: UtensilsCrossed,
  wallet: Wallet,
  creditCard: CreditCard,
  banknote: Banknote,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  loader: Loader2,
  alert: AlertCircle,
  info: Info,
  checkCircle: CheckCircle,
  error: XCircle,
  menu: Menu,
  location: MapPin,
  phone: Phone,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  sun: Sun,
  moon: Moon,
  filter: Filter,
  sort: SortAsc,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  play: Play,
  pause: Pause,
  volume: Volume2,
  volumeMute: VolumeX,
  maximize: Maximize,
  minimize: Minimize,
  send: Send,
  attach: Paperclip,
  image: ImageIcon,
  video: Video,
  smile: Smile,
  hashtag: Hash,
  mention: AtSign,
  globe: Globe,
  clock: Clock,
  calendar: Calendar,
  star: Star,
  flag: Flag,
  bookmark: Bookmark,
  moreHorizontal: MoreHorizontal,
  copy: Copy,
  external: ExternalLink,
  link: LinkIcon,
  qr: QrCode,
  scan: ScanLine,
  userPlus: UserPlus,
  users: Users,
  store: Store,
  package: Package,
  truck: Truck,
  receipt: Receipt,
  fileText: FileText,
  help: HelpCircle,
  shield: Shield,
  verified: BadgeCheck,
  trend: TrendingUp,
  chart: BarChart3,
  activity: Activity,
  zap: Zap,
  fire: Flame,
  sparkle: Sparkles,
  gift: Gift,
  coupon: Ticket,
  tag: Tag,
  percent: Percent,
  dollar: DollarSign,
  coins: Coins,
  bank: Landmark,
  building: Building2,
  navigation: Navigation,
};

const Icon = ({
  name,
  size = 24,
  strokeWidth = 2,
  className = "",
  color,
  fallback = null,
  ...props
}) => {
  const LucideIcon = iconMap[name] || iconMap.home;

  if (!LucideIcon) {
    return fallback || <span className={`inline-block ${className}`} style={{ width: size, height: size }} {...props}>◆</span>;
  }

  return (
    <LucideIcon
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      color={color}
      aria-hidden="true"
      {...props}
    />
  );
};

// Export both the component and the icon map for advanced usage
export { iconMap };
export default Icon;
